#  Лабораторна робота "Обробка табличних даних засобами бібліотеки Pandas"

__Метою__ лабораторної роботи є вивчення технологій первинного аналізу даних в середовищі бібліотеки Pandas, а саме здобуття навичок:
- працювати з даними використовуючи мову Python та пакет Pandas
- робити передобробку даних
- знаходити прості закономірності у даних

In [1]:
# підключити бібліотеки Pandas та NumPy
import pandas as pd
import numpy as np


In [37]:
import os
os.environ['comspec']='powershell.exe'

## 1. Створення  DataFrame

__DataFrame__ — це двовимірна неоднорідна таблична структура даних із змінюваними розмірами з іменованими вісями (рядками та стовпцями)

### ПРИКЛАДИ

In [2]:
# створити DataFrame з 1 колонкою з python-списка
df = pd.DataFrame(["Петя", "Вася", "Микола"])
print(df)
print(type(df))

        0
0    Петя
1    Вася
2  Микола
<class 'pandas.core.frame.DataFrame'>


In [3]:
# створити DataFrame з np-матриці розміром 10х10 випадкових чисел
mat = np.random.randint(100, 500, (10,10), dtype="int16")
print(mat)
df = pd.DataFrame(mat)
df

[[349 325 400 327 396 470 145 459 372 297]
 [142 117 141 234 134 144 301 349 463 242]
 [311 433 154 216 374 423 184 336 357 301]
 [338 194 301 415 289 389 134 211 381 494]
 [267 485 338 479 294 263 373 371 266 327]
 [300 261 284 456 224 398 225 366 248 453]
 [399 268 445 272 278 284 307 349 230 259]
 [161 176 441 376 312 116 106 461 178 205]
 [203 406 335 242 431 407 262 328 205 358]
 [494 401 465 487 440 240 482 139 180 161]]


0    1    2    3    4    5    6    7    8    9
0  349  325  400  327  396  470  145  459  372  297
1  142  117  141  234  134  144  301  349  463  242
2  311  433  154  216  374  423  184  336  357  301
3  338  194  301  415  289  389  134  211  381  494
4  267  485  338  479  294  263  373  371  266  327
5  300  261  284  456  224  398  225  366  248  453
6  399  268  445  272  278  284  307  349  230  259
7  161  176  441  376  312  116  106  461  178  205
8  203  406  335  242  431  407  262  328  205  358
9  494  401  465  487  440  240  482  139  180  161

In [4]:
# створити DataFrame з 2-мірного випадкового масиву з іменованими колонками
arr = np.random.random((5,3))
print(arr)
df = pd.DataFrame(arr, columns=["колонка 1", "колонка 2", "колонка 3"])
df

[[0.80185174 0.79019754 0.58358298]
 [0.20615509 0.5100786  0.31873334]
 [0.78977474 0.19538258 0.18889597]
 [0.32389238 0.10320048 0.69525488]
 [0.41978209 0.61073154 0.92273433]]


колонка 1  колонка 2  колонка 3
0   0.801852   0.790198   0.583583
1   0.206155   0.510079   0.318733
2   0.789775   0.195383   0.188896
3   0.323892   0.103200   0.695255
4   0.419782   0.610732   0.922734

In [5]:
# створити DataFrame з python-словника в якому ключ - це ім'я, а значення - 
# це масив з 5-ти випадкових чисел з модифікованими індексами рядків
d = {
    "Петя": np.random.random(5),
    "Вася" : np.random.random(5),
    "Микола":np.random.random(5)
    }
a = pd.DataFrame(d, index=[10,20,30,40,50])

In [6]:
a

Петя      Вася    Микола
10  0.333730  0.733378  0.112797
20  0.743791  0.709650  0.475750
30  0.754750  0.529558  0.617921
40  0.906442  0.446192  0.504989
50  0.917283  0.292090  0.412557

In [7]:
# створити dataFrame з ітеруємого об'єкта
name = ["Вася", "Петя", "Микола"]
rik = [2001, 2000, 2003]
name_rik = list(zip(name, rik))
print(name_rik)
df = pd.DataFrame(name_rik, columns=["Ім'я", "Рік народження"])
df

[('Вася', 2001), ('Петя', 2000), ('Микола', 2003)]


Ім'я  Рік народження
0    Вася            2001
1    Петя            2000
2  Микола            2003

In [8]:
str(name_rik[2])

"('Микола', 2003)"

In [9]:
pd.read_csv?

In [19]:
!(echo John, 2001 & echo Pedro, 2000 & echo Mykola, 2003) > file.csv
!type file.csv
# створити DataFrame з csv-файлу
df = pd.read_csv("file.csv", names=["Ім'я", "Рік народження"], encoding='latin-1')
df

John, 2001 
Pedro, 2000 
Mykola, 2003


Ім'я  Рік народження
0    John            2001
1   Pedro            2000
2  Mykola            2003

### ЗАВДАННЯ

In [24]:
# ЗАВДАННЯ 1.1: створити датафрейм з списку 10-ти простих чисел
df1_1 = pd.DataFrame([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
df1_1

0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9
9  0

In [26]:
# ЗАВДАННЯ 1.2: створити датафрейм з матриці 5х6 випадкових чисел з плаваючою точкою
df1_2 = pd.DataFrame(np.random.rand(5, 6))
df1_2

0         1         2         3         4         5
0  0.227418  0.252125  0.999967  0.605467  0.079593  0.258780
1  0.897481  0.613986  0.667615  0.081761  0.349757  0.918534
2  0.925892  0.585265  0.442353  0.651270  0.791007  0.204960
3  0.448070  0.042894  0.254819  0.666859  0.518645  0.924306
4  0.835395  0.768840  0.096226  0.143083  0.702529  0.409800

ЗАВДАННЯ 1.3: створити  DataFrame наступного вигляду:

|ім'я | прізвище| рік народження | телефон
|:-----|:------|:-----:|:-------:
|Петро| Петров| 2000| 222-222-2222
|Іван| Іванов| 2002| 333-333-3333
|Степан| Степанов| 2001| 444-444-4444

In [29]:
df1_3 = pd.DataFrame({
    "ім'я": ["Петро", "Іван", "Степан"],
    "прізвище": ["Петров", "Іванов", "Степанов"],
    "рік народження": ["2000", "2002", "2001"],
    "телефон": ["222-222-2222", "333-333-3333", "444-444-4444"]
})
df1_3

ім'я  прізвище рік народження       телефон
0   Петро    Петров           2000  222-222-2222
1    Іван    Іванов           2002  333-333-3333
2  Степан  Степанов           2001  444-444-4444

In [60]:
# ЗАВДАННЯ 1.4: створити датафрейм з 20 перших рядків excel-файлу, 
# який розташовано за адресою: 
# https://file-examples-com.github.io/uploads/2017/02/file_example_XLS_100.xls
df1_4 = pd.read_excel('ЖУРНАЛ ФІТ 3 курс.xlsx', sheet_name='12 група')
df1_4[:30]

Unnamed: 0         Unnamed: 1       Unnamed: 2    Unnamed: 3  \
0           N          Прізвище   Логін на Мооdle   Разовий PSW   
1           1        Абуєв І. У.         abuyev_і        111111   
2           2     Адамович В. О.      adamovіch_v        111111   
3           3    Андрієнко В. А.      andryenko_v        111111   
4           4     Білецька А. В.        blecjka_a        111111   
5           5    Бригинець Є. Б.     brіgіnecj_ye        111111   
6           6    Вернигора Д. В.      vernіgora_d        111111   
7           7      Галушко І. Р.       galushko_і        111111   
8           8       Гречко А. В.        grechko_a        111111   
9           9        Губар І. О.          gubar_і        111111   
10         10     Домніков І. А.       domnikov_i        111111   
11         11       Житник В. С.        zhіtnіk_v        111111   
12         12  Закревський В. В.    zakrevsjkіj_v        111111   
13         13  Капітоненко Н. С.    kapіtonenko_n        111111   
14         14        Кацап Р. Л.          kacap_r        111111   
15         15     Кірієнко Н. В.      kiriyenko_n        111111   
16         16  Козловський Д. О.    kozlovsjkij_d        111111   
17         17       Костюк М. Ю.        kostyuk_m        111111   
18         18     Леоненко В. В.       leonenko_v        111111   
19         19        Лисюк І. С.         lіsyuk_і        111111   
20         20    Лук`янець Б. В.     luk`yanecj_b        111111   
21         21   Максименко В. В.     maksіmenko_v        111111   
22         22       Марчук О. В.        marchuk_o        111111   
23         23      Мельник В. Ю.        meljnіk_v        111111   
24         24     Німченко В. В.      nіmchenko_v        111111   
25         25       Павлюк В. Р.        pavlyuk_v        111111   
26         26    Романенко Д. Д.      romanenko_d        111111   
27         27    Сиропятов І. О.     sіropyatov_і        111111   
28         28       Сокрут Д. Б.         sokrut_d        111111   
29         29   Степаненко М. В.     stepanenko_m        111111   

                                       Unnamed: 4     Unnamed: 5  \
0                       Репо дисципліни на GitHub  Вступний тест   
1                                             NaN            NaN   
2        https://github.com/Adamovych-002/ML-2023            NaN   
3                                             NaN            NaN   
4     https://github.com/Alya-Biletskaya/M.H..git            NaN   
5                                             NaN            NaN   
6                                             NaN            NaN   
7                                             NaN            NaN   
8                                             NaN            NaN   
9                                             NaN            NaN   
10     https://github.com/zzarxy/machine-learning            NaN   
11                                            NaN            NaN   
12                                            NaN            NaN   
13                                            NaN            NaN   
14                                            NaN            NaN   
15                                            NaN            NaN   
16           https://github.com/frayzzzy1/ML-2023            NaN   
17                                            NaN            NaN   
18                                            NaN            NaN   
19                                            NaN            NaN   
20                                            NaN            NaN   
21                                            NaN            NaN   
22                                            NaN            NaN   
23                                            NaN            NaN   
24                                            NaN            NaN   
25                                            NaN            NaN   
26                                            NaN            NaN   
27         https://gi

## 2. Інспектування DataFrame

__Інспектування__ - це процедури вивчення внутрішньої структури даних та вмісту датафрейма

### ПРИКЛАДИ

In [53]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [54]:
# отримати загальну інформацію про датасет
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [61]:
# вивести перші 3 рядкі
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [62]:
# вивести останні 2 рядки
titanic.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [63]:
# отримати імена колонок
col_names = titanic.columns
print(col_names)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [64]:
# вивести загальну статистику датасету - числові поля
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [65]:
# вивести статитсику текстового поля `Sex` 
titanic['Sex'].describe()

count      891
unique       2
top       male
freq       577
Name: Sex, dtype: object

In [66]:
# перевірити тип колонки датасету
type(titanic['Age'])

pandas.core.series.Series

In [67]:
# вивести перші 10 рядків деяких колонок
cols = ["Name", "Age", "Sex"]
titanic[cols].head(10)

Name   Age     Sex
0                            Braund, Mr. Owen Harris  22.0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                             Heikkinen, Miss. Laina  26.0  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                           Allen, Mr. William Henry  35.0    male
5                                   Moran, Mr. James   NaN    male
6                            McCarthy, Mr. Timothy J  54.0    male
7                     Palsson, Master. Gosta Leonard   2.0    male
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  female
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0  female

In [68]:
# вивести рядки з 100 по 110
titanic[100:110]

PassengerId  Survived  Pclass                              Name     Sex  \
100          101         0       3           Petranec, Miss. Matilda  female   
101          102         0       3  Petroff, Mr. Pastcho ("Pentcho")    male   
102          103         0       1         White, Mr. Richard Frasar    male   
103          104         0       3        Johansson, Mr. Gustaf Joel    male   
104          105         0       3    Gustafsson, Mr. Anders Vilhelm    male   
105          106         0       3             Mionoff, Mr. Stoytcho    male   
106          107         1       3  Salkjelsvik, Miss. Anna Kristine  female   
107          108         1       3            Moss, Mr. Albert Johan    male   
108          109         0       3                   Rekic, Mr. Tido    male   
109          110         1       3               Moran, Miss. Bertha  female   

      Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
100  28.0      0      0   349245   7.8958   NaN        S  
101   NaN      0      0   349215   7.8958   NaN        S  
102  21.0      0      1    35281  77.2875   D26        S  
103  33.0      0      0     7540   8.6542   NaN        S  
104  37.0      2      0  3101276   7.9250   NaN        S  
105  28.0      0      0   349207   7.8958   NaN        S  
106  21.0      0      0   343120   7.6500   NaN        S  
107   NaN      0      0   312991   7.7750   NaN        S  
108  38.0      0      0   349249   7.8958   NaN        S  
109   NaN      1      0   371110  24.1500   NaN        Q

In [69]:
# вивести тільки чоловіків
cond = titanic["Sex"] == "male"
titanic[cond]

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [70]:
# вивести рядки в яких пропущено значення поля `Age`
cond = titanic['Age'].isna()
titanic[cond].head(3)

PassengerId  Survived  Pclass                          Name     Sex  Age  \
5             6         0       3              Moran, Mr. James    male  NaN   
17           18         1       2  Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3       Masselmani, Mrs. Fatima  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S  
19      0      0    2649   7.2250   NaN        C

In [43]:
# вивести рядки з пасажирами вік яких з 30 до 50 років
cond = titanic['Age'].between(30, 50)
titanic[cond]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
13            14         0       3   
18            19         0       3   
..           ...       ...     ...   
872          873         0       1   
873          874         0       3   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
..                                                 ...     ...   ...    ...   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
4        0    373450   8.0500          NaN        S  
13       5    347082  31.2750          NaN        S  
18       0    345763  18.0000          NaN        S  
..     ...       ...      ...          ...      ...  
872      0       695   5.0000  B51 B53 B55        S  
873      0    345765   9.0000          NaN        S  
881      0    349257   7.8958          NaN        S  
885      5    382652  29.1250          NaN        Q  
890      0    370376   7.7500          NaN        Q  

[266 rows x 12 columns]

### ЗАВДАННЯ

In [71]:
# ЗАВДАННЯ 2.1: вивести характеристики датасету `titanic`
titanic.info(), titanic.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


(None,
        PassengerId    Survived      Pclass         Age       SibSp  \
 count   891.000000  891.000000  891.000000  714.000000  891.000000   
 mean    446.000000    0.383838    2.308642   29.699118    0.523008   
 std     257.353842    0.486592    0.836071   14.526497    1.102743   
 min       1.000000    0.000000    1.000000    0.420000    0.000000   
 25%     223.500000    0.000000    2.000000   20.125000    0.000000   
 50%     446.000000    0.000000    3.000000   28.000000    0.000000   
 75%     668.500000    1.000000    3.000000   38.000000    1.000000   
 max     891.000000    1.000000    3.000000   80.000000    8.000000   
 
             Parch        Fare  
 count  891.000000  891.000000  
 mean     0.381594   32.204208  
 std      0.806057   49.693429  
 min      0.000000    0.000000  
 25%      0.000000    7.910400  
 50%      0.000000   14.454200  
 75%      0.000000   31.000000  
 max      6.000000  512.329200  )

In [78]:
# ЗАВДАННЯ 2.2: вивести статистичні параметри полів `Age` та `Fare` датасету `titanic`
titanic[['Age','Fare']].describe()

Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [82]:
# ЗАВДАННЯ 2.3: пірахувати кількість записів в яких заповнені усі показчики
print("This file have " + str(titanic.dropna().shape[0]) + " fulfilled lines")

This file have 183 fulfilled lines


In [92]:
# ЗАВДАННЯ 2.4: пірахувати кількість виживших (survived=1) пасажирів жиночої статі (Sex=`female`)
print("Only " + str(titanic[(titanic["Sex"] == "female") & (titanic["Survived"] == 1)].shape[0]) + " females survived on Titanic.")
print("From " + str(titanic[titanic['Sex'] == 'female'].shape[0]) + " total females on Titanic.")

Only 233 females survived on Titanic.
From 314 total females on Titanic.


## 3. Перетворення датафреймів

__Перетворення__ - це сукупність операцій та методів для зміни структури та вмісту датафрейму та окремих його елементів

### ПРИКЛАДИ

In [93]:
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}

df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [94]:
# типи колонок та елементів в колонці
print(df["рейтинг"].dtype)
print(type(df['рейтинг']))

object
<class 'pandas.core.series.Series'>


In [95]:
# Перетворити тип колонки (показчика) 'рейтинг' в ціле числове
df['рейтинг'] = df['рейтинг'].astype("int8")
print(df["рейтинг"].dtype)

int8


In [96]:
# додати колонку "адреса"
df["адреса"] = ["Київ", "Бровари", "Фастів"]
df

ім'я  вік  рейтинг   адреса
0  Петя   22       10     Київ
1  Вася  200        3  Бровари
2  Галя   21        2   Фастів

In [97]:
#  збільшити значення "рейтинг" на 3
df['рейтинг'] = df['рейтинг'] + 3
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася  200        6  Бровари
2  Галя   21        5   Фастів

In [98]:
# виправити значення параметру 'вік' для імені 'Вася'
df.loc[1, "вік"] = 20
df

ім'я  вік  рейтинг   адреса
0  Петя   22       13     Київ
1  Вася   20        6  Бровари
2  Галя   21        5   Фастів

In [99]:
# видалити колонку `вік'
df.drop(columns='вік', inplace=True)
df

ім'я  рейтинг   адреса
0  Петя       13     Київ
1  Вася        6  Бровари
2  Галя        5   Фастів

In [100]:
# вивести 5 перших рядків датафрейму
titanic.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [101]:
# вивести 3 випадкових рядки датафрейму
titanic.sample(3)

PassengerId  Survived  Pclass  \
485          486         0       3   
426          427         1       2   
371          372         0       3   

                                            Name     Sex   Age  SibSp  Parch  \
485                       Lefebre, Miss. Jeannie  female   NaN      3      1   
426  Clarke, Mrs. Charles V (Ada Maria Winfield)  female  28.0      1      0   
371                    Wiklund, Mr. Jakob Alfred    male  18.0      1      0   

      Ticket     Fare Cabin Embarked  
485     4133  25.4667   NaN        S  
426     2003  26.0000   NaN        S  
371  3101267   6.4958   NaN        S

In [102]:
# відсортувати dataframe `titanic` за віком пасажиров
titanic.sort_values('Age')

PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander   
755          756         1       2                 Hamalainen, Master. Viljo   
644          645         1       3                    Baclini, Miss. Eugenie   
469          470         1       3             Baclini, Miss. Helene Barbara   
78            79         1       2             Caldwell, Master. Alden Gates   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
803    male  0.42      0      1        2625   8.5167   NaN        C  
755    male  0.67      1      1      250649  14.5000   NaN        S  
644  female  0.75      2      1        2666  19.2583   NaN        C  
469  female  0.75      2      1        2666  19.2583   NaN        C  
78     male  0.83      0      2      248738  29.0000   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
859    male   NaN      0      0        2629   7.2292   NaN        C  
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male   NaN      0      0      345777   9.5000   NaN        S  
878    male   NaN      0      0      349217   7.8958   NaN        S  
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [103]:
# перейменувати значення в `Embarked` стовпчику:
# С - Cherbourg
# Q - Queenstown
# S - Southampton
titanic['Embarked'].replace({"C": "Cherbourg", "Q": "Queenstown", "S": "Southampton"},
                           inplace=True)
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin     Embarked  
0        0         A/5 21171   7.2500   NaN  Southampton  
1        0          PC 17599  71.2833   C85    Cherbourg  
2        0  STON/O2. 3101282   7.9250   NaN  Southampton  
3        0            113803  53.1000  C123  Southampton  
4        0            373450   8.0500   NaN  Southampton  
..     ...               ...      ...   ...          ...  
886      0            211536  13.0000   NaN  Southampton  
887      0            112053  30.0000   B42  Southampton  
888      2        W./C. 6607  23.4500   NaN  Southampton  
889      0            111369  30.0000  C148    Cherbourg  
890      0            370376   7.7500   NaN   Queenstown  

[891 rows x 12 columns]

In [104]:
# підрахувати кількість пасажирів 1-го класу (Pclass=1)
cond = titanic['Pclass'] == 1
kol_pass = titanic[cond]['PassengerId'].count()
kol_pass

216

In [105]:
# замінити відсутні номери кают на ''
titanic.fillna({"Cabin": "***"}, inplace=True)
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin     Embarked  
0      0         A/5 21171   7.2500   ***  Southampton  
1      0          PC 17599  71.2833   C85    Cherbourg  
2      0  STON/O2. 3101282   7.9250   ***  Southampton

In [106]:
# видалити рядки в яких є відсутні значення 
titanic.dropna(axis=0, how='any', inplace=True)
titanic.shape

(712, 12)

### ЗАВДАННЯ

In [107]:
# ЗАВДАННЯ 3.1: створити датафрейм з словника d
d = {
    "ім'я"    : ["Петя", "Вася", "Галя"],
    "вік"     : [22, 200 , 21],
    "рейтинг" : ["10", "3", "2"]
}
df = pd.DataFrame(d)
df

ім'я  вік рейтинг
0  Петя   22      10
1  Вася  200       3
2  Галя   21       2

In [108]:
# ЗАВДАННЯ 3.2: додати до `df` стовбчик з показчиком 
# `рік завершення школи` = [2018, 2020, 200]
df['рік завершення школи'] = ['2018','2020','200']
print(df)

   ім'я  вік рейтинг рік завершення школи
0  Петя   22      10                 2018
1  Вася  200       3                 2020
2  Галя   21       2                  200


In [111]:
# ЗАВДАННЯ 3.3: виправити 'рік завершення школи' з 200 на 2020
df.loc[2, "рік завершення школи"] = 2020
print(df)

   ім'я  вік рейтинг рік завершення школи
0  Петя   22      10                 2018
1  Вася  200       3                 2020
2  Галя   21       2                 2020


In [112]:
# завантаження датасету `titanic` (https://ansmirnov.ru/kaggle-titanic-dataset/)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)

In [113]:
# ЗАВДАННЯ 3.4: вивести з датасету `titanic` останні 10 записів 
titanic.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [138]:
# ЗАВДАННЯ 3.5: вибрати з датасету `titanic` рядки з пасажирами чоловічої статі віком 
# від 20 до 30 років, які подорожували 2 класом
titanic[(titanic['Sex'] == 'male') & (titanic['Pclass'] == 2) & (titanic["Age"].between(20, 30))]

PassengerId  Survived  Pclass  \
72            73         0       2   
117          118         0       2   
120          121         0       2   
134          135         0       2   
135          136         0       2   
178          179         0       2   
213          214         0       2   
219          220         0       2   
221          222         0       2   
234          235         0       2   
242          243         0       2   
308          309         0       2   
342          343         0       2   
343          344         0       2   
361          362         0       2   
398          399         0       2   
418          419         0       2   
529          530         0       2   
551          552         0       2   
562          563         0       2   
619          620         0       2   
655          656         0       2   
658          659         0       2   
666          667         0       2   
685          686         0       2   
728          729         0       2   
733          734         0       2   
734          735         0       2   
848          849         0       2   
861          862         0       2   
864          865         0       2   
883          884         0       2   
886          887         0       2   

                                           Name   Sex   Age  SibSp  Parch  \
72                         Hood, Mr. Ambrose Jr  male  21.0      0      0   
117             Turpin, Mr. William John Robert  male  29.0      1      0   
120                 Hickman, Mr. Stanley George  male  21.0      2      0   
134              Sobey, Mr. Samuel James Hayden  male  25.0      0      0   
135                          Richard, Mr. Emile  male  23.0      0      0   
178                          Hale, Mr. Reginald  male  30.0      0      0   
213                 Givard, Mr. Hans Kristensen  male  30.0      0      0   
219                          Harris, Mr. Walter  male  30.0      0      0   
221                        Bracken, Mr. James H  male  27.0      0      0   
234           Leyson, Mr. Robert William Norman  male  24.0      0      0   
242             Coleridge, Mr. Reginald Charles  male  29.0      0      0   
308                         Abelson, Mr. Samuel  male  30.0      1      0   
342                  Collander, Mr. Erik Gustaf  male  28.0      0      0   
343  Sedgwick, Mr. Charles Frederick Waddington  male  25.0      0      0   
361                   del Carlo, Mr. Sebastiano  male  29.0      1      0   
398                            Pain, Dr. Alfred  male  23.0      0      0   
418                  Matthews, Mr. William John  male  30.0      0      0   
529                 Hocking, Mr. Richard George  male  23.0      2      1   
551                 Sharp, Mr. Percival James R  male  27.0      0      0   
562                  Norman, Mr. Robert Douglas  male  28.0      0      0   
619                         Gavey, Mr. Lawrence  male  26.0      0      0   
655                   Hickman, Mr. Leonard Mark  male  24.0      2      0   
658                Eitemiller, Mr. George Floyd  male  23.0      0      0   
666                 Butler, Mr. Reginald Fenton  male  25.0      0      0   
685      Laroche, Mr. Joseph Philippe Lemercier  male  25.0      1      2   
728             Bryhl, Mr. Kurt Arnold Gottfrid  male  25.0      1      0   
733                  Berriman, Mr. William John  male  23.0      0      0   
734                Troupiansky, Mr. Moses Aaron  male  23.0      0      0   
848                           Harper, Rev. John  male  28.0      0      1   
861                 Giles, Mr. Frederick Edward  male  21.0      1      0   
864                      Gill, Mr. John William  male  24.0      0      0   
883               Banfield, Mr. Frederick James  male  28.0      0      0   
886                       Montvila, Rev. Juozas  male  27.0      0      0   

               Ticket     Fare Cabin Embarked  
72       S.O.C. 14879  73.5000   NaN        S

In [122]:
# ЗАВДАННЯ 3.6: видалити з датасету `titanic` рядки з пасажирами у яких відсутня
# вартість (fare) квітка
df = titanic['Fare'].dropna()
df

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [139]:
# ЗАВДАННЯ 3.7: підрахувати середню вартість квитка у каютах 1-го класу
avg_price = np.mean(titanic[(titanic['Pclass'] == 1)]['Fare'])
print(avg_price)

84.15468749999992


## 4. Агрегація датафреймів

__Агрегація__ - це функції отримання агрегованих даних шляхом групування об'єктів датафрейма 

### ПРИКЛАДИ

In [125]:
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [126]:
# підрахувати середній вік пасажирів по класам кают
group_by_class = titanic.groupby(["Pclass"])
avg_age = group_by_class["Age"].mean()
print(avg_age)

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64


In [127]:
# підрахувати кількість чоловіків та жінок по класам кают
man_woman_count = titanic.groupby(["Pclass", "Sex"])["Sex"].count()
man_woman_count

Pclass  Sex   
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: Sex, dtype: int64

In [128]:
# створити таблицю в якій підраховано середню вартість білетів (Fare) в залежності
# від місця посадки (Embarked) по класам кают
tickets_cost = titanic.pivot_table(values="Fare", index="Pclass", columns="Embarked",
                   aggfunc=np.mean)
tickets_cost

Embarked           C          Q          S
Pclass                                    
1         104.718529  90.000000  70.364862
2          25.358335  12.350000  20.327439
3          11.214083  11.183393  14.644083

### ЗАВДАННЯ

In [132]:
# ЗАВДАННЯ 4.1: отримати відомості про максимальний вік жінок та чоловіків
max_age = titanic.groupby(titanic['Sex'])['Age'].max()
print(max_age)

Sex
female    63.0
male      80.0
Name: Age, dtype: float64


___ЗАВДАННЯ 4.2___

на основі даних з `titanic` побудувати таблицю наступного вигляду:

Pclass  |Male  | Female
--------|------|-------
1  | ... | ...
2  | ... | ...
3  | ... | ...

де замість `...` повинно бути кількість виживших (Survived) чоловіків та жінок відповідно

In [137]:
surv_table = titanic.pivot_table(values="Survived", index="Pclass", columns="Sex",
                   aggfunc=np.sum)
surv_table

Sex     female  male
Pclass              
1           91    45
2           70    17
3           72    47