# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [ ]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [2]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [3]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x18b37ba9960
byteorder:  little
byteswap:  False
type: int32


In [4]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [6]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [7]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.02506413 0.61687664 0.94360484]
 [0.05679345 0.47060627 0.54444321]
 [0.55530962 0.7293736  0.76939009]]


In [8]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [9]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.02506413 0.61687664 0.94360484]
 [0.05679345 0.47060627 0.54444321]
 [0.55530962 0.7293736  0.76939009]]
...
float64
(3, 3)
3
2
9
8
72


In [10]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [11]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.random.rand(3, 4)
print(arr1_1)

[[0.90907385 0.15481638 0.41717397 0.62062414]
 [0.98518436 0.72155283 0.97296565 0.59884798]
 [0.91816691 0.79013623 0.10458382 0.64808974]]


In [12]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(["Sokrut", "Danylo", "Petro", "Taras", "FIT"])
print(arr1_2)

['Sokrut' 'Danylo' 'Petro' 'Taras' 'FIT']


In [14]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3, 4))
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [15]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [17]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [18]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [19]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.array([False]*9)
arr2_1 = arr2_1.reshape(3, 1, 3)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [23]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3, 3))
arr2_2 = arr2_2.astype('int')
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2).reshape(3, -1)
print(arr2_3)

[[10 12]
 [14 16]
 [18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [26]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [27]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[20 25 33 16]
 [36 44 44 27]
 [15 34 35 10]
 [30 10 25 19]]


In [28]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

27


In [29]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[30 10 25 19]


In [30]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[20 25 33 16]
 [36 44 44 27]]


In [31]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[25 33]
 [44 44]
 [34 35]
 [10 25]]


In [32]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[20 25 33 16]
 [15 34 35 10]]


In [ ]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

### ЗАВДАННЯ 3

In [34]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.linspace(10, 100, 20)
arr3_1 = arr3_1.reshape((4, 5))
print(arr3_1)

[[ 10.          14.73684211  19.47368421  24.21052632  28.94736842]
 [ 33.68421053  38.42105263  43.15789474  47.89473684  52.63157895]
 [ 57.36842105  62.10526316  66.84210526  71.57894737  76.31578947]
 [ 81.05263158  85.78947368  90.52631579  95.26315789 100.        ]]


In [36]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1][2]
print(el3_2)

43.1578947368421


In [37]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[33.68421053 38.42105263 43.15789474 47.89473684 52.63157895]


In [39]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[:,2]
print(vect3_4)

[19.47368421 43.15789474 66.84210526 90.52631579]


In [41]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[38.42105263 43.15789474]
 [62.10526316 66.84210526]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [42]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [44]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.01968998 0.66067689 0.55079952 0.34255964 0.65127482]
 [0.48230208 0.64624251 0.95486291 0.16267489 0.37342754]
 [0.17739301 0.91909184 0.67614166 0.95231993 0.16439379]
 [0.79593103 0.16108424 0.52269827 0.73365707 0.24627851]
 [0.500951   0.39782182 0.00567786 0.95845101 0.16253089]]
...
[0.01968998 0.64624251 0.67614166 0.73365707 0.16253089]


In [45]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.01968998 0.48230208 0.17739301 0.79593103 0.500951  ]
 [0.66067689 0.64624251 0.91909184 0.16108424 0.39782182]
 [0.55079952 0.95486291 0.67614166 0.52269827 0.00567786]
 [0.34255964 0.16267489 0.95231993 0.73365707 0.95845101]
 [0.65127482 0.37342754 0.16439379 0.24627851 0.16253089]]


In [46]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

0.11768564591344735


In [47]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[-0.91451576  1.82784857 -1.30717598 -0.70466136  1.85482685]
 [-0.6745686   2.06254791 -0.40299661 -2.56017185  2.25115849]
 [ 0.08159322 -0.73527556  1.18645771  1.66119293 -2.35481305]
 [ 0.42609517 -1.69999724  1.02940681  1.33433692 -0.86461018]
 [ 1.95428124 -0.63157387 -1.09653364  0.51168398  0.10656111]]


### ЗАВАДАННЯ 4

In [53]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.round(np.linspace(100, 200, 36), 1).reshape((6, 6))
print(mat4_1)

[[100.  102.9 105.7 108.6 111.4 114.3]
 [117.1 120.  122.9 125.7 128.6 131.4]
 [134.3 137.1 140.  142.9 145.7 148.6]
 [151.4 154.3 157.1 160.  162.9 165.7]
 [168.6 171.4 174.3 177.1 180.  182.9]
 [185.7 188.6 191.4 194.3 197.1 200. ]]


In [55]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[100. 120. 140. 160. 180. 200.]


In [56]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[100.  117.1 134.3 151.4 168.6 185.7]
 [102.9 120.  137.1 154.3 171.4 188.6]
 [105.7 122.9 140.  157.1 174.3 191.4]
 [108.6 125.7 142.9 160.  177.1 194.3]
 [111.4 128.6 145.7 162.9 180.  197.1]
 [114.3 131.4 148.6 165.7 182.9 200. ]]


In [58]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.round(np.linalg.inv(mat4_1), 1)
print(inv4_4)

[[ -0.1  -6.    4.    4.    4.   -5.9]
 [  6.   -0.  -10.    0.    0.    4. ]
 [ -4.   10.   -0.  -10.    0.    4. ]
 [ -4.    0.   10.    0.  -10.    4. ]
 [ -4.    0.    0.   10.   -0.   -6. ]
 [  6.1  -4.   -4.   -4.    6.   -0.1]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [59]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [60]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [61]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [62]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [63]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [64]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [65]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [66]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [67]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\Family\AppData\Local\Temp\ipykernel_16208\3347190385.py:2: RuntimeWarning: divide by zero encountered in true_divide
  K = N / M


In [68]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [69]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [70]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [71]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [72]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [73]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[8 4 2 7 4]
[8 4 2 7 4]
1697498270864 1697498270864
[8 4 2 7 4]
1697498270864 1697498270192


In [74]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [89]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.round(np.random.rand(4,3),2)
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[0.06 0.09 0.8 ]
 [0.9  0.42 0.35]
 [0.97 0.75 0.98]
 [0.78 0.56 0.45]]
[0.95 1.67 2.7  1.79]


In [90]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

0.06


In [91]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[100.06 100.09 100.8 ]
 [100.9  100.42 100.35]
 [100.97 100.75 100.98]
 [100.78 100.56 100.45]]


In [92]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.array([np.dot(mat5_1, np.diag(mat5_3))])
print(mat5_4)

[[ 95.8254 167.5734 271.3336 179.723 ]]


In [99]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_4.T), axis=1)
print('Matrix rank is %s' % np.linalg.matrix_rank(mat5_5))

Matrix rank is 4
